let i = Math.floor(Math.random() * 100);

const locators = {
    url: 'https://automationexercise.com/',
    home_page_logo: '.left-sidebar',
    login_button: '[class = "nav navbar-nav"] :nth-child(4)',
    sign_up_form: '.signup-form',
    login_form: '.login-form',
    sign_up_name: 'input[data-qa="signup-name"]',
    sign_up_email: 'input[data-qa="signup-email"]',
    sign_up_button: 'button[data-qa="signup-button"]',
    login_form: '.login-form',
    login_title: '.top[for="id_gender1"]',
    login_password: '.form-control[name="password"]',
    login_day: '#days',
    login_month: '#months',
    login_year: '#years',
    login_checkbox_1: '#newsletter',
    login_checkbox_2: '#optin',
    firstname: '#first_name',
    lastname: '#last_name',
    company: '#company',
    address: '#address1',
    address2: '#address2',
    country: '#country',
    state: '#state',
    city: '#city',
    zipcode: '#zipcode',
    mobile_number: '#mobile_number',
    create_account: 'button.btn-default[data-qa="create-account"]',
    account_created: 'div.row div[class="col-sm-9 col-sm-offset-1"]',
    continue: '.pull-right a.btn-primary',
    loged_user: 'ul[class="nav navbar-nav"] :nth-child(10) a b',
    delete_account: 'ul[class="nav navbar-nav"] :nth-child(5) a ',
    account_deleted: '[class="col-sm-9 col-sm-offset-1"] h2 b',
    log_email: '[data-qa="login-email"]',
    log_password: '[data-qa="login-password"]',
    log_button: '[data-qa="login-button"]',
    log_error_message: '.login-form p',
    logout: 'ul[class="nav navbar-nav"] :nth-child(4) a',
    sign_up_error_message: '.signup-form p',
    contact_us: 'div[class="shop-menu pull-right"] ul :nth-child(8) a',
    contacy_form: 'div.contact-form',
    contact_name: 'input.form-control[data-qa="name"]',
    contact_email: 'input.form-control[data-qa="email"]',
    contact_subject: 'input.form-control[data-qa="subject"]',
    contact_message: '#message',
    contact_file: '.form-control[name="upload_file"]',
    contact_submit: 'input[type="submit"]',
    contacts_succses_mesage: '[class="status alert alert-success"]',
    contacts_hom_button: '#form-section a ',
    test_cases_button: 'div[class="shop-menu pull-right"] ul :nth-child(5) a',
    test_cases: 'h2[class="title text-center"] b'
}

const values = {
    sign_up_name: "Poghos",
    sign_up_email: `Poghosyan${i}@gmail.com`,
    login_password: "12345",
    login_day: 20,
    login_month: "July",
    login_year: "2010",
    firstname: 'Poghos',
    lastname: 'Poghosyan',
    company: 'NRGaming',
    address: 'North Street',
    address2: 'North Street 2',
    state: 'Erevan',
    city: 'Erevan',
    zipcode: '0411',
    mobile_number: '07799999999',
    log_email: `Poghosyan1@gmail.com`,
    log_password: "12345",
    log_incorect_email: "ppppppppppp@gmail.com",
    log_incorrect_password: "asdfghj"
}

export {locators, values};
